### ISSUE TITLE
[issue] this.items.length is not a function

### ISSUE THREAD

**Issue by nutzmdm** [mrk-j/paginga#10]
I tried to use this very interresting plugin to paginate an <ul><li> list but I encountered this error:

this.items.length is not a function

I use jquery 3.1.0

**Comment by nutzmdm** [comment]
I tried to replace .size by .length but same issue

**Comment by nutzmdm** [comment]
I think this should be this.items.length and not this.items.length()

**Comment by mrk-j** [comment]
Hi @nutzmdm, thanks for pointing this out. You are correct! The documentation says `.size()` is deprecated since jQuery 1.8.

Oops! 😬 

I will fix this in a few minutes.
